[package]
name = "pktdump_async"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
pktmon = { path = "../../", features = ["tokio"] }
tokio = { version = "1.45.0", features = ["full"] }
futures = "0.3.31"
colog = "1.3.0"
log = "0.4.25"
